### ISSUE TITLE
Makefile defaults to install

### ISSUE THREAD

**Issue by ManuLinares** [Nooberieno/jura#14]
Makefile should default to only build the binary.

Including sudo isn't good, also the line "rm jura.c" removes the source code after installing.
Should be "rm jura"

**Comment by ManuLinares** [comment]
I understand, I recommend keeping the Makefile and fixing it.

But there is something you missed: https://github.com/Nooberieno/jura/blob/b215286aaa9f57aaaf75d85ff6293513b9eeac8b/Makefile#L6

See that line, it is deleting the source file "jura.c".

None of the Makefile options should remove the source file. The source "jura.c" should always remain.

**Comment by Nooberieno** [comment]
This problem has been fixed for both the standalone and mainline version scheduled for the 5.0 release. I will now close this issue
